#!/bin/sh
# Copyright (c) 2017 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

treeroot="$(dirname "$0")/.."
cd "${treeroot}"

echo "Removing collation tables from ICU data file configuration"

# IMPORTANT: The 'EMPTY_CONFIGURATION tag will be searched
#            in collocal.mk by copy_data.sh to determine whether
#            the generated data file contains collation data or not.

cat > "${treeroot}"/source/data/coll/collocal.mk <<END
# EMPTY_CONFIGURATION auto-generated by $(basename "$0") script.
# This should only be used with icu_enable_system_collation = true
COLLATION_CLDR_VERSION = %version%
COLLATION_SYNTHETIC_ALIAS =
COLLATION_ALIAS_SOURCE = \$(COLLATION_SYNTHETIC_ALIAS)
COLLATION_EMPTY_SOURCE =
COLLATION_SOURCE = \$(COLLATION_EMPTY_SOURCE)
END
